app:
  security:
    secret: ${AUTH_SECRET}
    salt: ${AUTH_SALT}

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: users
      username: mongoadmin
      password: password
      uuid-representation: standard
      authentication-database: admin

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
