services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  api_authentification:
    build: ../
    container_name: api_authentification
    ports:
      - "8080:8080"